title: Sean van Mulligen
description: Writing code, learning, and most importantly, having fun.

url: https://blog.vanmulligen.ca
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
# markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact

social:
   github: seanvm
   email: sean@vanmulligen.ca

google_analytics: "UA-129657336-1"
